# Site settings
title: American Express | American Express on Github
description: "American Express Open Source"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: /img/blueboxR.png

# Hero
hero: 
   # hero_img: Frontpanel.jpg
    hero_title: American Express on Github
    hero_description: American Express Open Source

# Contact
api_token: # Enter API token here

# Amexparallax
amexparallax:
    parallax_img: parallaxbckgrndimg.jpeg
    header_img: Frontpanel.jpg

paginate: 3
paginate_path: "/blogs/page:num/"
future: true

permalink: pretty

# Social settings
facebook: http://facebook.com/AmericanExpressUS
twitter: http://twitter.com/americanexpress
#instagram: http://instagram.com
youtube: http://youtube.com/user/AmericanExpress
#skype: skype:obaez_design?userinfo
# feed: yes

# Footer
copyright: © 2015 American Express - All rights reserved

# Build settings
markdown: kramdown

#career site details
career: 
    web: https://careers.americanexpress.com/?inav=footer_careers
    life: https://careers.americanexpress.com/Life

osf:
    email: osf@aexp.com

#blogs url
blogs: /blogs    

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

gems:
- jekyll-paginate

# Theme Settings
analytics: 
google_verification:

##port default 4000
#port: 4000

